### ISSUE TITLE
Release a new version on PyPI to include ts_tree_cursor_current_field_name binding

### ISSUE THREAD

**Issue by 2yz** [tree-sitter/py-tree-sitter#19] opened 2020-01-14 06:24 UTC

**Comment by yagebu** [comment] 2020-01-17 17:12
When installing from PyPI, I get the deprecation errors that I fixed in https://github.com/tree-sitter/py-tree-sitter/commit/0413e8a0466a242a9a35e04264dd2dbc194f1299, so it seems the code there doesn't match the tag here, which is another good reason for a new release :)

**Comment by anandsork** [comment] 2020-01-23 13:38
I am also struggling with current_field_name of TreeCursor. I always get None
Is this the same issue?

I am trying to do following.
some_node: Node = rootNode[0][1] # Deep in Some level
cursor: TreeCursor = some_node.walk()
field_name = cursor.current_field_name() # This always gives None

   I had to ask the parent node to get child by the field_name...  I am writing a walker and do some checks based on what he current node's name is..  
  Any help is appreciated..

**Comment by CamilleTeruel** [comment] 2020-05-15 06:49
@maxbrunsfeld This issue can be closed. Fixed with the release of 0.1.1 on pypi.

**Comment by CamilleTeruel** [comment] 2020-05-15 06:57
@anandsork 

> I always get None
Is this the same issue?

No this is an issue to release a new version of the pypi package.

> I am trying to do following.
some_node: Node = rootNode.children[0].children[1] # Deep in Some level
cursor: TreeCursor = some_node.walk()
field_name = cursor.current_field_name() # This always gives None

IIRC, you have to `walk()` from the root node.

**Comment by sogaiu** [comment] 2020-09-24 06:26
@CamilleTeruel @maxbrunsfeld At least currently, according to: http://tree-sitter.github.io/tree-sitter/using-parsers#other-tree-operations

> You can initialize a cursor from any node:
>
> TSTreeCursor ts_tree_cursor_new(TSNode);

Also according to: https://github.com/tree-sitter/py-tree-sitter/blob/master/tree_sitter/binding.c#L188-L194

```
static PyMethodDef node_methods[] = {
  {
    .ml_name = "walk",
    .ml_meth = (PyCFunction)node_walk,
    .ml_flags = METH_NOARGS,
    .ml_doc = "walk()\n--\n\n\
               Get a tree cursor for walking the tree starting at this node.",
  },
```

It seems like the intent is to be able to invoke `walk` from any node.  The value of `.ml_doc` seems to suggest this, as it says:

> Get a tree cursor for walking the tree starting at this node.

I also encountered similar behavior as that reported by @anandsork in: https://github.com/tree-sitter/py-tree-sitter/issues/19#issuecomment-577684776

Please clarify as to whether one is supposed to be able to `walk` from any node.

Being able to use `walk` from any node seems quite useful and calls to it appear to succeed with sensible output for the following sort of code:
```
node = some_node.child_by_field_name("value")
cursor = node.walk()
print(cursor)
print(cursor.node)
```
However, a subsequent:
```
print(cursor.current_field_name())
```
returns `None` here even when the original node was obtained via `child_by_field_name`.

Is this a bug?

**Comment by sogaiu** [comment] 2020-09-28 02:14
@anandsork I think it is not a bug.

https://github.com/tree-sitter/tree-sitter/issues/567#issuecomment-595348892 explains how things work currently:

> Yeah, this is actually the expected behavior. The cursor only "walks" within the node that it started from, and it can't go outside of it. This is possible to change, but it would add some complexity. Maybe it's worth it though, because this has confused people before.

In order to access a field name for a node, it appears necessary to create the cursor not on the node itself but on an ancestor (so, parent will work).  I ran a test now and found that I could get back a non-None appropriate value via `current_field_name()`.

@maxbrunsfeld In comment referenced above you mentioned the possibility of changing how things work.  I don't suppose that's still a possibility?

**Comment by lunixbochs** [comment] 2022-02-08 16:25
broke that out into a new issue, closing the original here

**Closed by lunixbochs** 2022-02-08 16:25 UTC
Labels: feature_request
