### ISSUE TITLE
node.is_named, what about node.name?

### ISSUE THREAD

**Issue by NorthIsUp** [tree-sitter/py-tree-sitter#96] opened 2022-03-15 21:48 UTC
would the ts api support getting the name of a node?

**Comment by ubergarm** [comment] 2022-10-04 14:26
possibly a duplicate of #80 

I've found the `text` field useful in my use-case to access the actual code bytes e.g.
```python
if (node.type == "function_definition"):
    print(node.text.decode("utf-8"))
```

**Comment by maxbrunsfeld** [comment] 2022-10-04 22:24
`node.type`

**Closed** 2023-09-04 06:09 UTC
