### ISSUE TITLE
[tree-sitter-python]  `No matching distribution found for tree-sitter-python`

### ISSUE THREAD

**Issue by shmuel44** [tree-sitter/py-tree-sitter#206] opened 2024-03-10 18:10 UTC
I am having trouble following the instructions in the `Usage` section of the README file. 
The example in the README [suggests](https://github.com/tree-sitter/py-tree-sitter/blob/master/README.md#:~:text=pip%20install%20tree%2Dsitter%2Dpython) that I can install the `tree-sitter-python` library from PyPi. However, when I try to do so by running `pip install tree-sitter-python`, I encounter an error.
```
ERROR: Could not find a version that satisfies the requirement tree-sitter-python (from versions: none)
ERROR: No matching distribution found for tree-sitter-python
```

**Comment by ObserverOfTime** [comment] 2024-03-10 18:11
Duplicate of #205

**Closed by ObserverOfTime** 2024-03-10 18:11 UTC
